// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockfileOps is a mock of fileOps interface.
type MockfileOps struct {
	ctrl     *gomock.Controller
	recorder *MockfileOpsMockRecorder
	isgomock struct{}
}

// MockfileOpsMockRecorder is the mock recorder for MockfileOps.
type MockfileOpsMockRecorder struct {
	mock *MockfileOps
}

// NewMockfileOps creates a new mock instance.
func NewMockfileOps(ctrl *gomock.Controller) *MockfileOps {
	mock := &MockfileOps{ctrl: ctrl}
	mock.recorder = &MockfileOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileOps) EXPECT() *MockfileOpsMockRecorder {
	return m.recorder
}

// CopyFile mocks base method.
func (m *MockfileOps) CopyFile(srcPath, dstPath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CopyFile", srcPath, dstPath)
	ret0, _ := ret[0].(error)
	return ret0
}

// CopyFile indicates an expected call of CopyFile.
func (mr *MockfileOpsMockRecorder) CopyFile(srcPath, dstPath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CopyFile", reflect.TypeOf((*MockfileOps)(nil).CopyFile), srcPath, dstPath)
}

// FileExists mocks base method.
func (m *MockfileOps) FileExists(filePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", filePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockfileOpsMockRecorder) FileExists(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockfileOps)(nil).FileExists), filePath)
}

// FindAllFiles mocks base method.
func (m *MockfileOps) FindAllFiles(dir string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllFiles", dir)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllFiles indicates an expected call of FindAllFiles.
func (mr *MockfileOpsMockRecorder) FindAllFiles(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllFiles", reflect.TypeOf((*MockfileOps)(nil).FindAllFiles), dir)
}

// GetCurrentDir mocks base method.
func (m *MockfileOps) GetCurrentDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentDir indicates an expected call of GetCurrentDir.
func (mr *MockfileOpsMockRecorder) GetCurrentDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentDir", reflect.TypeOf((*MockfileOps)(nil).GetCurrentDir))
}

// MkdirAll mocks base method.
func (m *MockfileOps) MkdirAll(path string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockfileOpsMockRecorder) MkdirAll(path, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockfileOps)(nil).MkdirAll), path, perm)
}

// ReadFileNormalized mocks base method.
func (m *MockfileOps) ReadFileNormalized(filePath string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReadFileNormalized", filePath)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ReadFileNormalized indicates an expected call of ReadFileNormalized.
func (mr *MockfileOpsMockRecorder) ReadFileNormalized(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReadFileNormalized", reflect.TypeOf((*MockfileOps)(nil).ReadFileNormalized), filePath)
}

// RemoveFile mocks base method.
func (m *MockfileOps) RemoveFile(filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFile", filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFile indicates an expected call of RemoveFile.
func (mr *MockfileOpsMockRecorder) RemoveFile(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFile", reflect.TypeOf((*MockfileOps)(nil).RemoveFile), filePath)
}

// Stat mocks base method.
func (m *MockfileOps) Stat(filePath string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", filePath)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockfileOpsMockRecorder) Stat(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockfileOps)(nil).Stat), filePath)
}

// WriteFile mocks base method.
func (m *MockfileOps) WriteFile(filePath, content string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "WriteFile", filePath, content, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// WriteFile indicates an expected call of WriteFile.
func (mr *MockfileOpsMockRecorder) WriteFile(filePath, content, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "WriteFile", reflect.TypeOf((*MockfileOps)(nil).WriteFile), filePath, content, perm)
}

// MockcomparatorService is a mock of comparatorService interface.
type MockcomparatorService struct {
	ctrl     *gomock.Controller
	recorder *MockcomparatorServiceMockRecorder
	isgomock struct{}
}

// MockcomparatorServiceMockRecorder is the mock recorder for MockcomparatorService.
type MockcomparatorServiceMockRecorder struct {
	mock *MockcomparatorService
}

// NewMockcomparatorService creates a new mock instance.
func NewMockcomparatorService(ctrl *gomock.Controller) *MockcomparatorService {
	mock := &MockcomparatorService{ctrl: ctrl}
	mock.recorder = &MockcomparatorServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcomparatorService) EXPECT() *MockcomparatorServiceMockRecorder {
	return m.recorder
}

// AreEqual mocks base method.
func (m *MockcomparatorService) AreEqual(file1, file2 string, overwriteHeaders bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AreEqual", file1, file2, overwriteHeaders)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AreEqual indicates an expected call of AreEqual.
func (mr *MockcomparatorServiceMockRecorder) AreEqual(file1, file2, overwriteHeaders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AreEqual", reflect.TypeOf((*MockcomparatorService)(nil).AreEqual), file1, file2, overwriteHeaders)
}

// MockcopierService is a mock of copierService interface.
type MockcopierService struct {
	ctrl     *gomock.Controller
	recorder *MockcopierServiceMockRecorder
	isgomock struct{}
}

// MockcopierServiceMockRecorder is the mock recorder for MockcopierService.
type MockcopierServiceMockRecorder struct {
	mock *MockcopierService
}

// NewMockcopierService creates a new mock instance.
func NewMockcopierService(ctrl *gomock.Controller) *MockcopierService {
	mock := &MockcopierService{ctrl: ctrl}
	mock.recorder = &MockcopierServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockcopierService) EXPECT() *MockcopierServiceMockRecorder {
	return m.recorder
}

// Copy mocks base method.
func (m *MockcopierService) Copy(srcPath, dstPath string, overwriteHeaders bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", srcPath, dstPath, overwriteHeaders)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockcopierServiceMockRecorder) Copy(srcPath, dstPath, overwriteHeaders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockcopierService)(nil).Copy), srcPath, dstPath, overwriteHeaders)
}

// MockfilterService is a mock of filterService interface.
type MockfilterService struct {
	ctrl     *gomock.Controller
	recorder *MockfilterServiceMockRecorder
	isgomock struct{}
}

// MockfilterServiceMockRecorder is the mock recorder for MockfilterService.
type MockfilterServiceMockRecorder struct {
	mock *MockfilterService
}

// NewMockfilterService creates a new mock instance.
func NewMockfilterService(ctrl *gomock.Controller) *MockfilterService {
	mock := &MockfilterService{ctrl: ctrl}
	mock.recorder = &MockfilterServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfilterService) EXPECT() *MockfilterServiceMockRecorder {
	return m.recorder
}

// CleanupExtraFilesByPatterns mocks base method.
func (m *MockfilterService) CleanupExtraFilesByPatterns(srcFiles []string, srcBase, dstBase string, patterns []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExtraFilesByPatterns", srcFiles, srcBase, dstBase, patterns)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExtraFilesByPatterns indicates an expected call of CleanupExtraFilesByPatterns.
func (mr *MockfilterServiceMockRecorder) CleanupExtraFilesByPatterns(srcFiles, srcBase, dstBase, patterns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExtraFilesByPatterns", reflect.TypeOf((*MockfilterService)(nil).CleanupExtraFilesByPatterns), srcFiles, srcBase, dstBase, patterns)
}

// FindFilesByPatterns mocks base method.
func (m *MockfilterService) FindFilesByPatterns(dir string, patterns []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFilesByPatterns", dir, patterns)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFilesByPatterns indicates an expected call of FindFilesByPatterns.
func (mr *MockfilterServiceMockRecorder) FindFilesByPatterns(dir, patterns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFilesByPatterns", reflect.TypeOf((*MockfilterService)(nil).FindFilesByPatterns), dir, patterns)
}

// GetFilePatterns mocks base method.
func (m *MockfilterService) GetFilePatterns(flagValue string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilePatterns", flagValue)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilePatterns indicates an expected call of GetFilePatterns.
func (mr *MockfilterServiceMockRecorder) GetFilePatterns(flagValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilePatterns", reflect.TypeOf((*MockfilterService)(nil).GetFilePatterns), flagValue)
}
