// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/yanodintsovmercuryo/cursync/pkg/config (interfaces: ConfigRepositoryInterface)
//
// Generated by this command:
//
//	mockgen -destination=mocks/repository_mocks.go -package=mocks github.com/yanodintsovmercuryo/cursync/pkg/config ConfigRepositoryInterface
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	config "github.com/yanodintsovmercuryo/cursync/pkg/config"
	gomock "go.uber.org/mock/gomock"
)

// MockConfigRepositoryInterface is a mock of ConfigRepositoryInterface interface.
type MockConfigRepositoryInterface struct {
	ctrl     *gomock.Controller
	recorder *MockConfigRepositoryInterfaceMockRecorder
	isgomock struct{}
}

// MockConfigRepositoryInterfaceMockRecorder is the mock recorder for MockConfigRepositoryInterface.
type MockConfigRepositoryInterfaceMockRecorder struct {
	mock *MockConfigRepositoryInterface
}

// NewMockConfigRepositoryInterface creates a new mock instance.
func NewMockConfigRepositoryInterface(ctrl *gomock.Controller) *MockConfigRepositoryInterface {
	mock := &MockConfigRepositoryInterface{ctrl: ctrl}
	mock.recorder = &MockConfigRepositoryInterfaceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockConfigRepositoryInterface) EXPECT() *MockConfigRepositoryInterfaceMockRecorder {
	return m.recorder
}

// Get mocks base method.
func (m *MockConfigRepositoryInterface) Get(cfg *config.Config, key string) (any, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", cfg, key)
	ret0, _ := ret[0].(any)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockConfigRepositoryInterfaceMockRecorder) Get(cfg, key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockConfigRepositoryInterface)(nil).Get), cfg, key)
}

// GetAll mocks base method.
func (m *MockConfigRepositoryInterface) GetAll(cfg *config.Config) map[string]any {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetAll", cfg)
	ret0, _ := ret[0].(map[string]any)
	return ret0
}

// GetAll indicates an expected call of GetAll.
func (mr *MockConfigRepositoryInterfaceMockRecorder) GetAll(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetAll", reflect.TypeOf((*MockConfigRepositoryInterface)(nil).GetAll), cfg)
}

// Load mocks base method.
func (m *MockConfigRepositoryInterface) Load() (*config.Config, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Load")
	ret0, _ := ret[0].(*config.Config)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Load indicates an expected call of Load.
func (mr *MockConfigRepositoryInterfaceMockRecorder) Load() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Load", reflect.TypeOf((*MockConfigRepositoryInterface)(nil).Load))
}

// LoadOrDefault mocks base method.
func (m *MockConfigRepositoryInterface) LoadOrDefault() *config.Config {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "LoadOrDefault")
	ret0, _ := ret[0].(*config.Config)
	return ret0
}

// LoadOrDefault indicates an expected call of LoadOrDefault.
func (mr *MockConfigRepositoryInterfaceMockRecorder) LoadOrDefault() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "LoadOrDefault", reflect.TypeOf((*MockConfigRepositoryInterface)(nil).LoadOrDefault))
}

// Save mocks base method.
func (m *MockConfigRepositoryInterface) Save(cfg *config.Config) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Save", cfg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Save indicates an expected call of Save.
func (mr *MockConfigRepositoryInterfaceMockRecorder) Save(cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Save", reflect.TypeOf((*MockConfigRepositoryInterface)(nil).Save), cfg)
}

// Set mocks base method.
func (m *MockConfigRepositoryInterface) Set(cfg *config.Config, key string, value any) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", cfg, key, value)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockConfigRepositoryInterfaceMockRecorder) Set(cfg, key, value any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockConfigRepositoryInterface)(nil).Set), cfg, key, value)
}
