// Code generated by MockGen. DO NOT EDIT.
// Source: service.go
//
// Generated by this command:
//
//	mockgen -source=service.go -destination=mocks/mocks.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	os "os"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockoutputService is a mock of outputService interface.
type MockoutputService struct {
	ctrl     *gomock.Controller
	recorder *MockoutputServiceMockRecorder
	isgomock struct{}
}

// MockoutputServiceMockRecorder is the mock recorder for MockoutputService.
type MockoutputServiceMockRecorder struct {
	mock *MockoutputService
}

// NewMockoutputService creates a new mock instance.
func NewMockoutputService(ctrl *gomock.Controller) *MockoutputService {
	mock := &MockoutputService{ctrl: ctrl}
	mock.recorder = &MockoutputServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockoutputService) EXPECT() *MockoutputServiceMockRecorder {
	return m.recorder
}

// PrintErrorf mocks base method.
func (m *MockoutputService) PrintErrorf(format string, args ...any) {
	m.ctrl.T.Helper()
	varargs := []any{format}
	for _, a := range args {
		varargs = append(varargs, a)
	}
	m.ctrl.Call(m, "PrintErrorf", varargs...)
}

// PrintErrorf indicates an expected call of PrintErrorf.
func (mr *MockoutputServiceMockRecorder) PrintErrorf(format any, args ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{format}, args...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintErrorf", reflect.TypeOf((*MockoutputService)(nil).PrintErrorf), varargs...)
}

// PrintOperation mocks base method.
func (m *MockoutputService) PrintOperation(operationType, relativePath string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintOperation", operationType, relativePath)
}

// PrintOperation indicates an expected call of PrintOperation.
func (mr *MockoutputServiceMockRecorder) PrintOperation(operationType, relativePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintOperation", reflect.TypeOf((*MockoutputService)(nil).PrintOperation), operationType, relativePath)
}

// PrintOperationWithTarget mocks base method.
func (m *MockoutputService) PrintOperationWithTarget(operationType, relativePath, target string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "PrintOperationWithTarget", operationType, relativePath, target)
}

// PrintOperationWithTarget indicates an expected call of PrintOperationWithTarget.
func (mr *MockoutputServiceMockRecorder) PrintOperationWithTarget(operationType, relativePath, target any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrintOperationWithTarget", reflect.TypeOf((*MockoutputService)(nil).PrintOperationWithTarget), operationType, relativePath, target)
}

// MockpathUtils is a mock of pathUtils interface.
type MockpathUtils struct {
	ctrl     *gomock.Controller
	recorder *MockpathUtilsMockRecorder
	isgomock struct{}
}

// MockpathUtilsMockRecorder is the mock recorder for MockpathUtils.
type MockpathUtilsMockRecorder struct {
	mock *MockpathUtils
}

// NewMockpathUtils creates a new mock instance.
func NewMockpathUtils(ctrl *gomock.Controller) *MockpathUtils {
	mock := &MockpathUtils{ctrl: ctrl}
	mock.recorder = &MockpathUtilsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockpathUtils) EXPECT() *MockpathUtilsMockRecorder {
	return m.recorder
}

// GetBaseName mocks base method.
func (m *MockpathUtils) GetBaseName(filePath string) string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetBaseName", filePath)
	ret0, _ := ret[0].(string)
	return ret0
}

// GetBaseName indicates an expected call of GetBaseName.
func (mr *MockpathUtilsMockRecorder) GetBaseName(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetBaseName", reflect.TypeOf((*MockpathUtils)(nil).GetBaseName), filePath)
}

// GetRelativePath mocks base method.
func (m *MockpathUtils) GetRelativePath(filePath, baseDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetRelativePath", filePath, baseDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetRelativePath indicates an expected call of GetRelativePath.
func (mr *MockpathUtilsMockRecorder) GetRelativePath(filePath, baseDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetRelativePath", reflect.TypeOf((*MockpathUtils)(nil).GetRelativePath), filePath, baseDir)
}

// RecreateDirectoryStructure mocks base method.
func (m *MockpathUtils) RecreateDirectoryStructure(srcPath, srcBase, dstBase string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RecreateDirectoryStructure", srcPath, srcBase, dstBase)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// RecreateDirectoryStructure indicates an expected call of RecreateDirectoryStructure.
func (mr *MockpathUtilsMockRecorder) RecreateDirectoryStructure(srcPath, srcBase, dstBase any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RecreateDirectoryStructure", reflect.TypeOf((*MockpathUtils)(nil).RecreateDirectoryStructure), srcPath, srcBase, dstBase)
}

// MockgitOps is a mock of gitOps interface.
type MockgitOps struct {
	ctrl     *gomock.Controller
	recorder *MockgitOpsMockRecorder
	isgomock struct{}
}

// MockgitOpsMockRecorder is the mock recorder for MockgitOps.
type MockgitOpsMockRecorder struct {
	mock *MockgitOps
}

// NewMockgitOps creates a new mock instance.
func NewMockgitOps(ctrl *gomock.Controller) *MockgitOps {
	mock := &MockgitOps{ctrl: ctrl}
	mock.recorder = &MockgitOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockgitOps) EXPECT() *MockgitOpsMockRecorder {
	return m.recorder
}

// CommitChanges mocks base method.
func (m *MockgitOps) CommitChanges(repoDir, commitMessage string, withoutPush bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CommitChanges", repoDir, commitMessage, withoutPush)
	ret0, _ := ret[0].(error)
	return ret0
}

// CommitChanges indicates an expected call of CommitChanges.
func (mr *MockgitOpsMockRecorder) CommitChanges(repoDir, commitMessage, withoutPush any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CommitChanges", reflect.TypeOf((*MockgitOps)(nil).CommitChanges), repoDir, commitMessage, withoutPush)
}

// GetGitRootDir mocks base method.
func (m *MockgitOps) GetGitRootDir(startDir string) (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetGitRootDir", startDir)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetGitRootDir indicates an expected call of GetGitRootDir.
func (mr *MockgitOpsMockRecorder) GetGitRootDir(startDir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetGitRootDir", reflect.TypeOf((*MockgitOps)(nil).GetGitRootDir), startDir)
}

// MockfileService is a mock of fileService interface.
type MockfileService struct {
	ctrl     *gomock.Controller
	recorder *MockfileServiceMockRecorder
	isgomock struct{}
}

// MockfileServiceMockRecorder is the mock recorder for MockfileService.
type MockfileServiceMockRecorder struct {
	mock *MockfileService
}

// NewMockfileService creates a new mock instance.
func NewMockfileService(ctrl *gomock.Controller) *MockfileService {
	mock := &MockfileService{ctrl: ctrl}
	mock.recorder = &MockfileServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileService) EXPECT() *MockfileServiceMockRecorder {
	return m.recorder
}

// AreEqual mocks base method.
func (m *MockfileService) AreEqual(file1, file2 string, overwriteHeaders bool) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AreEqual", file1, file2, overwriteHeaders)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// AreEqual indicates an expected call of AreEqual.
func (mr *MockfileServiceMockRecorder) AreEqual(file1, file2, overwriteHeaders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AreEqual", reflect.TypeOf((*MockfileService)(nil).AreEqual), file1, file2, overwriteHeaders)
}

// CleanupExtraFilesByPatterns mocks base method.
func (m *MockfileService) CleanupExtraFilesByPatterns(srcFiles []string, srcBase, dstBase string, patterns []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CleanupExtraFilesByPatterns", srcFiles, srcBase, dstBase, patterns)
	ret0, _ := ret[0].(error)
	return ret0
}

// CleanupExtraFilesByPatterns indicates an expected call of CleanupExtraFilesByPatterns.
func (mr *MockfileServiceMockRecorder) CleanupExtraFilesByPatterns(srcFiles, srcBase, dstBase, patterns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CleanupExtraFilesByPatterns", reflect.TypeOf((*MockfileService)(nil).CleanupExtraFilesByPatterns), srcFiles, srcBase, dstBase, patterns)
}

// Copy mocks base method.
func (m *MockfileService) Copy(srcPath, dstPath string, overwriteHeaders bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Copy", srcPath, dstPath, overwriteHeaders)
	ret0, _ := ret[0].(error)
	return ret0
}

// Copy indicates an expected call of Copy.
func (mr *MockfileServiceMockRecorder) Copy(srcPath, dstPath, overwriteHeaders any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Copy", reflect.TypeOf((*MockfileService)(nil).Copy), srcPath, dstPath, overwriteHeaders)
}

// FindFilesByPatterns mocks base method.
func (m *MockfileService) FindFilesByPatterns(dir string, patterns []string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindFilesByPatterns", dir, patterns)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindFilesByPatterns indicates an expected call of FindFilesByPatterns.
func (mr *MockfileServiceMockRecorder) FindFilesByPatterns(dir, patterns any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindFilesByPatterns", reflect.TypeOf((*MockfileService)(nil).FindFilesByPatterns), dir, patterns)
}

// GetFilePatterns mocks base method.
func (m *MockfileService) GetFilePatterns(flagValue string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetFilePatterns", flagValue)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetFilePatterns indicates an expected call of GetFilePatterns.
func (mr *MockfileServiceMockRecorder) GetFilePatterns(flagValue any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetFilePatterns", reflect.TypeOf((*MockfileService)(nil).GetFilePatterns), flagValue)
}

// MockfileOps is a mock of fileOps interface.
type MockfileOps struct {
	ctrl     *gomock.Controller
	recorder *MockfileOpsMockRecorder
	isgomock struct{}
}

// MockfileOpsMockRecorder is the mock recorder for MockfileOps.
type MockfileOpsMockRecorder struct {
	mock *MockfileOps
}

// NewMockfileOps creates a new mock instance.
func NewMockfileOps(ctrl *gomock.Controller) *MockfileOps {
	mock := &MockfileOps{ctrl: ctrl}
	mock.recorder = &MockfileOpsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockfileOps) EXPECT() *MockfileOpsMockRecorder {
	return m.recorder
}

// FileExists mocks base method.
func (m *MockfileOps) FileExists(filePath string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FileExists", filePath)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FileExists indicates an expected call of FileExists.
func (mr *MockfileOpsMockRecorder) FileExists(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FileExists", reflect.TypeOf((*MockfileOps)(nil).FileExists), filePath)
}

// FindAllFiles mocks base method.
func (m *MockfileOps) FindAllFiles(dir string) ([]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "FindAllFiles", dir)
	ret0, _ := ret[0].([]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FindAllFiles indicates an expected call of FindAllFiles.
func (mr *MockfileOpsMockRecorder) FindAllFiles(dir any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FindAllFiles", reflect.TypeOf((*MockfileOps)(nil).FindAllFiles), dir)
}

// GetCurrentDir mocks base method.
func (m *MockfileOps) GetCurrentDir() (string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetCurrentDir")
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetCurrentDir indicates an expected call of GetCurrentDir.
func (mr *MockfileOpsMockRecorder) GetCurrentDir() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetCurrentDir", reflect.TypeOf((*MockfileOps)(nil).GetCurrentDir))
}

// MkdirAll mocks base method.
func (m *MockfileOps) MkdirAll(path string, perm os.FileMode) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MkdirAll", path, perm)
	ret0, _ := ret[0].(error)
	return ret0
}

// MkdirAll indicates an expected call of MkdirAll.
func (mr *MockfileOpsMockRecorder) MkdirAll(path, perm any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MkdirAll", reflect.TypeOf((*MockfileOps)(nil).MkdirAll), path, perm)
}

// RemoveFile mocks base method.
func (m *MockfileOps) RemoveFile(filePath string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveFile", filePath)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveFile indicates an expected call of RemoveFile.
func (mr *MockfileOpsMockRecorder) RemoveFile(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveFile", reflect.TypeOf((*MockfileOps)(nil).RemoveFile), filePath)
}

// Stat mocks base method.
func (m *MockfileOps) Stat(filePath string) (os.FileInfo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stat", filePath)
	ret0, _ := ret[0].(os.FileInfo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stat indicates an expected call of Stat.
func (mr *MockfileOpsMockRecorder) Stat(filePath any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stat", reflect.TypeOf((*MockfileOps)(nil).Stat), filePath)
}
